default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USER"] %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: jumpstart_gh_actions_development

test:
  <<: *default
  database: jumpstart_gh_actions_test

production:
  <<: *default
  database: jumpstart_gh_actions_production
  username: jumpstart_gh_actions
  password: <%= ENV['JUMPSTART_GH_ACTIONS_DATABASE_PASSWORD'] %>
